services:
  db:
    container_name: db
    image: postgres:13
    env_file:
      - ./.env.local
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build: 
      context: ./backend
      dockerfile: go.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ./backend/.env.local
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build: 
      context: ./frontend
      dockerfile: nextjs.dockerfile
    ports:
      - 3001:3001
    depends_on:
      - goapp
    env_file:
      - ./frontend/.env.local  
volumes:
  pgdata: {}